language: python
sudo: false
dist: trusty

python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
  - pip install numpy
  - bash tools/install_solvers.sh
  - python setup.py build_ext
  - python setup.py build_py
  - python setup.py install

# command to run tests
script:
  - bash tools/test.sh
